name: name_plus
description: Automatically increment File & Directory name and create.
version: 0.0.2
homepage: https://github.com/thitlwincoder/name_plus

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
